---
title: "Problem Set 3"
author: "Nate Gonzales-Hess"
date: "2025-04-21"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(here)
library(tidyverse)
library(brms)
library(tidybayes)
library(patchwork)
library(rethinking)
library(MASS)
```

```{r}
# Load Data
data(eagles)
```

```{r message=FALSE, warning=FALSE}
# Define priors
priors =get_prior(y | trials(n) ~ P + V + A, 
          data = eagles, 
          family = binomial(link = "logit"))
```
```{r}
# Define Model
m1 <- brm(
  data = eagles,
  family = binomial(link = "logit"),
  y | trials(n) ~ P + V + A,
  prior = c(
    prior(normal(0, 1.5), class = "Intercept"),
    prior(normal(0, 0.5), class = "b", coef = "PS"),
    prior(normal(0, 0.5), class = "b", coef = "VS"),
    prior(normal(0, 0.5), class = "b", coef = "AI")
    ),
  iter = 5000, warmup = 1000, 
  chains = 4, cores = 4,
  seed = 213,
  file = here("files/models/ps5.1")
)
```
