---
title: "Week 4 Day 1"
author: "Nate Gonzales-Hess"
date: "2025-04-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(brms)
library(tidybayes)
library(patchwork)
library(rethinking)
```

```{r}
sppnames <- c( "afarensis","africanus","habilis","boisei",
               "rudolfensis","ergaster","sapiens")
brainvolcc <- c( 438 , 452 , 612, 521, 752, 871, 1350 )
masskg <- c( 37.0 , 35.5 , 34.5 , 41.5 , 55.5 , 61.0 , 53.5 )
d <- data.frame( species=sppnames , brain=brainvolcc , mass=masskg )
rethinking::precis(d)
```


```{r}
d <- d %>% 
  mutate(across(c(mass, brain),
                rethinking::standardize, 
                .names = "{.col}_std"))
```

```{r}
m1 <- brm(
  data=d,
  family=gaussian,
  brain_std ~ mass_std,
  prior = c( prior(normal(.5, 1), class=Intercept),
             prior(normal(0, 10), class=b),
             prior(exponential(1), class=sigma)),
  iter=2000, warmup=1000, seed=5, chains=1,
  file=here("files/models/41.1"))

posterior_summary(m1)


```
Predictive models and causal models are two different animals!

```{r}
m2 <- brm(
  data=d,
  family=gaussian,
  brain_std ~ mass_std + I(mass_std^2) + I(mass_std^3) + I(mass_std^4) + I(mass_std^5),
  prior = c( prior(normal(.5, 1), class=Intercept),
             prior(normal(0, 10), class=b),
             prior(exponential(1), class=sigma)),
  iter=2000, warmup=1000, seed=5, chains=1,
  file=here("files/models/41.2"))

posterior_summary(m2)

```

```{r}
m2r <- brm(
  data=d,
  family=gaussian,
  brain_std ~ mass_std + I(mass_std^2) + I(mass_std^3) + 
    I(mass_std^4) + I(mass_std^5),
  prior = c( prior(normal(.5, 1), class=Intercept),
             prior(normal(0, 1), class=b),
             prior(exponential(1), class=sigma)),
  iter=2000, warmup=1000, seed=5, chains=1,
  file=here("files/models/41.2r"))
```

```{r}
library(loo)
loo(m1)

```
elpd: Expected log posterior density
```